# site settings
title: RPP
subtitle: The Roma People's Project at Columbia University
email: cristiana.grigore@columbia.edu
description: "The Roma People's Project at Columbia University will spotlight the Roma people and expand Roma studies by examining topics such as identity and stigma, mobility and displacement, and archival research and digital scholarship. The RPP aims to build a digital platform that identifies, examines, and curates material about how Roma define themselves and how others have represented them."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address1: 406 Schermerhorn Hall, MC 5501 
street_address2: 1190 Amsterdam Ave
city: New York
state: NY
zip_code: 10027
country: United States of America
phone: (212) 851-5845

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/romapeoplesproject/
github_url: https://github.com/roma-project/roma-project.github.io/
instagram_url: https://www.instagram.com/romapeoplesproject/
twitter_url: https://twitter.com/RPP_Columbia

# build settings
markdown: kramdown

sass:
  style: compressed
